### ISSUE TITLE
Stopped working for the last couple of days.

### ISSUE THREAD

**Issue by bullyard** [center-key/gulp-w3c-html-validator#10]
It seems that the ip system tries to connect to, does no longer allow connections on port 80.
```
Error: connect ETIMEDOUT 128.30.52.39:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:134:14) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '128.30.52.39',
  port: 80,
  response: undefined
}
```

**Comment by pilafmon** [comment]
There haven't been any changes to the port handling in a long time.  Can you provide some more information, including how you are calling the plugin.
